// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.API.Persistence.Entities.DB;

#nullable disable

namespace NotificationService.API.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20250411140932_LoggingEntity")]
    partial class LoggingEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.API.Persistence.Entities.DB.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "en",
                            Name = "Registration",
                            Subject = "Registration confirmation",
                            Text = "\n                    <html>\n                        <head>\n                            <style>\n                                body {\n                                    font-family: Arial, sans-serif;\n                                    font-size: 16px;\n                                    color: #333;\n                                }\n                                p {\n                                    margin: 0 0 8px 0;\n                                }\n                            </style>\n                        </head>\n                        <body>\n                            <p style=\"padding-bottom: 16px;\">Hello <strong>{name}</strong>,</p>\n\n                            <p>Welcome to our sports center! We are very excited that you have decided to become part of our community.</p>\n                            <p>To fully utilize all the features, we recommend logging in and exploring your new account.</p>\n                            <p>If you have any questions or need assistance, please do not hesitate to contact us.</p>\n\n                            <p>Thank you for registering and we wish you many great experiences!</p>\n\n                            <p style=\"padding-top: 16px;\">Best regards,<br/>\n                            <em>Customer Support Team</em></p>\n                        </body>\n                    </html>"
                        },
                        new
                        {
                            Id = 2,
                            Language = "en",
                            Name = "Verification",
                            Subject = "Account verification",
                            Text = "\n                    <html>\n                        <head>\n                            <style>\n                                body {\n                                    font-family: Arial, sans-serif;\n                                    font-size: 16px;\n                                    color: #333;\n                                }\n                                p {\n                                    margin: 0 0 8px 0;\n                                }\n                            </style>\n                        </head>\n                        <body>\n                            <p style=\"padding-bottom: 16px;\">Hello <strong>{name}</strong>,</p>\n\n                            <p>Please verify your email address by clicking the following link:</p>\n                            <p><a href=\"{link}\" style=\"color: #1a73e8;\">{link}</a></p>\n                            <p>If you did not make this request, you can safely ignore this email.</p>\n\n                            <p>Thank you,</p>\n                            <p style=\"padding-top: 16px;\">Best regards,<br/>\n                            <em>Customer Support Team</em></p>\n                        </body>\n                    </html>"
                        },
                        new
                        {
                            Id = 3,
                            Language = "en",
                            Name = "PasswordReset",
                            Subject = "Password reset",
                            Text = "\n                    <html>\n                        <head>\n                            <style>\n                                body {\n                                    font-family: Arial, sans-serif;\n                                    font-size: 16px;\n                                    color: #333;\n                                }\n                                p {\n                                    margin: 0 0 8px 0;\n                                }\n                            </style>\n                        </head>\n                        <body>\n                            <p style=\"padding-bottom: 16px;\">Hello <strong>{name}</strong>,</p>\n\n                            <p>To reset your password, click the following link:</p>\n                            <p><a href=\"{link}\" style=\"color: #1a73e8;\">{link}</a></p>\n                            <p>If you did not make this request, please ignore this email.</p>\n\n                            <p>Thank you,</p>\n                            <p style=\"padding-top: 16px;\">Best regards,<br/>\n                            <em>Customer Support Team</em></p>\n                        </body>\n                    </html>"
                        },
                        new
                        {
                            Id = 4,
                            Language = "en",
                            Name = "BookingConfirmation",
                            Subject = "Reservation confirmation",
                            Text = "\n                    <html>\n                        <head>\n                            <style>\n                                body {\n                                    font-family: Arial, sans-serif;\n                                    font-size: 16px;\n                                    color: #333;\n                                }\n                                p {\n                                    margin: 0 0 8px 0;\n                                }\n                            </style>\n                        </head>\n                        <body>\n                            <p style=\"padding-bottom: 16px;\">Hello <strong>{name}</strong>,</p>\n\n                            <p>Your reservation on event {eventname}, has been was created.</p>\n                            <p><strong>Date and time:</strong> {datetime}</p>\n                            <p>If you have any questions or need to modify your reservation, feel free to contact us.</p>\n\n                            <p>Thank you,</p>\n                            <p style=\"padding-top: 16px;\">Best regards,<br/>\n                            <em>Customer Support Team</em></p>\n                        </body>\n                    </html>"
                        },
                        new
                        {
                            Id = 5,
                            Language = "en",
                            Name = "BookingCancellation",
                            Subject = "Reservation cancelation",
                            Text = "\n                    <html>\n                        <head>\n                            <style>\n                                body {\n                                    font-family: Arial, sans-serif;\n                                    font-size: 16px;\n                                    color: #333;\n                                }\n                                p {\n                                    margin: 0 0 8px 0;\n                                }\n                            </style>\n                        </head>\n                        <body>\n                            <p style=\"padding-bottom: 16px;\">Hello <strong>{name}</strong>,</p>\n\n                            <p>Your reservation on event{eventname}, has been canceled.</p>\n                            <p><strong>Date and time:</strong> {datetime}</p>\n\n                            <p>Thank you,</p>\n                            <p style=\"padding-top: 16px;\">Best regards,<br/>\n                            <em>Customer Support Team</em></p>\n                        </body>\n                    </html>"
                        });
                });

            modelBuilder.Entity("src.NotificationService.API.Persistence.Entities.DB.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NotificationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
