@NotificationService.API_HostAddress = https://notificationservice.thankfulflower-27b66160.polandcentral.azurecontainerapps.io

GET {{NotificationService.API_HostAddress}}/notification/
Accept: application/json

###
