name: 'Build and test'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet-version: ['8.0.x']

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --results-directory TestOutput --logger "trx;logfilename=${{ matrix.os }}-${{ matrix.dotnet-version }}.trx"
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.dotnet-version }}
        path: TestOutput/${{ matrix.os }}-${{ matrix.dotnet-version }}.trx
  report:
    needs: build_and_test
    name: Post test results
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v2
      with:
        artifact: /test-results-(.*)/
        name: Test report on $1
        path: '*.trx'
        reporter: dotnet-trx
