name: 'Build and Push to ACR'
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  prepare:
    name: 'Prepare'
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.environment.outputs.env }}
    steps:
      - name: Determine Environment
        id: environment
        run: |
          if [[ "${{ github.ref }}" =~ refs/tags/^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "env=Production" >> $GITHUB_OUTPUT
            exit 0
          elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
            echo "env=Development" >> $GITHUB_OUTPUT
            exit 0
          elif [[ "${{ github.ref }}" =~ refs/tags/^[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc\.[0-9]+)$ ]]; then
            echo "env=Staging" >> $GITHUB_OUTPUT
            exit 0
          fi
          exit 1
  push_image:
    name: 'Build and Push ${{ matrix.image }} to ACR'
    runs-on: ubuntu-latest
    needs: prepare
    environment: ${{ needs.prepare.outputs.env }}
    strategy:
      matrix:
        include:
          - image: adminsettings
            dockerfile: src/AdminSettings.API/Dockerfile
          - image: analyticsservice
            dockerfile: src/AnalyticsService.API/Analytics/Dockerfile
          - image: admindashboard
            dockerfile: src/UserService.API/Dockerfile
          - image: angularproject
            path: src/AngularProject
          - image: authservice
            dockerfile: src/AuthService.API/Dockerfile
          - image: bookingservice
            dockerfile: src/BookingService.API/Dockerfile
          - image: notificationservice
            dockerfile: src/NotificationService.API/Dockerfile
          - image: paymentservice
            dockerfile: src/PaymentService.API/Dockerfile
          - image: userservice
            dockerfile: src/UserService.API/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ACR Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Patch env for frontend
        if: ${{ matrix.image }} == 'angularproject'
        run: echo ${{ secrets.ANGULAR_ENV }} > src/AngularProject/src/enviroments/enviroment.ts
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.path }}"
          file: "${{ matrix.dockerfile || 'Dockerfile' }}"
          push: true
          tags: ${{ secrets.ACR_URL }}/cicd/${{ matrix.image }}:${{ vars.IMAGE_TAG }}
