name: 'Build and Push to ACR'
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  push_image:
    environment: 'Development'
    strategy:
      matrix:
        include:
          - image: authservice
            dockerfile: src/AuthService.API/Dockerfile
          - image: bookingservice
            dockerfile: src/BookingService.API/Dockerfile
          - image: notificationservice
            dockerfile: src/NotificationService.API/Dockerfile
          - image: userservice
            dockerfile: src/UserService.API/Dockerfile
    name: 'Build and Push ${{ matrix.image }} to ACR'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ACR Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: cicd/${{ matrix.image }}:${{ vars.IMAGE_TAG }}